//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Playerok.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int Id { get; set; }
        public int NameGameId { get; set; }
        public int CatygoryGameId { get; set; }
        public int DeveloperGameId { get; set; }
        public decimal Cost { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual CetagoriesGames CetagoriesGames { get; set; }
        public virtual DevelopersGames DevelopersGames { get; set; }
        public virtual NamesGames NamesGames { get; set; }


        public virtual string GameImage
        {
            get
            {
                if (Photo == null)
                {
                    Photo = "basePhoto.png";
                }
                return System.IO.Path.GetFullPath($"../../Resources/GamesImages/") + Photo;
            }
        
        }

        public virtual string CostGame
        {
            get {

                string stringCost = Convert.ToString(Cost);

                if (Cost == 0)
                {
                    stringCost = "FREE";
                }

                return stringCost;
                    
            }
        }
    }
}
