//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apteka.Model
{
    using Apteka.Properties;
    using System;
    using System.Collections.Generic;

    public partial class Medications
    {
        public int Id { get; set; }
        public int MedicationNameId { get; set; }
        public int DiagnosisId { get; set; }
        public int ManufacturerId { get; set; }
        public int FormRealeseId { get; set; }
        public decimal Cost { get; set; }
        public int Discount { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public int Count { get; set; }

        public virtual Diagnoses Diagnoses { get; set; }
        public virtual FormRealeses FormRealeses { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual MedicationsName MedicationsName { get; set; }


        public virtual decimal CostDisc
        {
            get
            {
                return Cost - (Cost / 100 * Discount);
            }
        }

        public virtual string PhotoDir
        {
            get
            {
                string path = "/Resources/images/";

                if (string.IsNullOrEmpty(Photo))
                {
                    Photo = "default.png";
                }

                return path + Photo;
            }
        }


    }

}
